{
	'name': "Validador de transferencias",
	'summary': "Agrega claves para cada empleado y solicita esa clave al momento de validar una transferencia",
	'author': 'Develogers',
	'website': 'https://develogers.com',
	'support': 'especialistas@develogers.com',
	'live_test_url': 'https://demo.develogers.com',
	'license': 'LGPL-3',
	'category': 'Extra Tools',
	'version': '17.0.1.0.0',
	'maintainer': 'Dany Chavez',
	'depends': [
     	'base',
		'stock',
  		'stock_account',
		'hr',
	],
	'data': [
		'views/stock_picking_views.xml',
		'views/hr_employee_views.xml',
  		'views/stock_valuation_layer_views.xml',
	],
	"external_dependencies": {"python": ["hashlib"]},
	'images': ['static/description/banner.gif'],
	'installable': True,
	'application': False,
	'auto_install': False,
	'secuence': '1',
}
